# Generated by cpp11: do not edit by hand

cpp_version <- function() {
  .Call(`_cellxgenedp_cpp_version`)
}

cpp_jmespath <- function(data, path) {
  .Call(`_cellxgenedp_cpp_jmespath`, data, path)
}
